name: Build and Push Docker Image

on:
  release:
    types:
      - published

jobs:
  publish:
    if: github.event_name == 'release' && github.event.action == 'published' && github.server_url != 'https://github.com'
    uses: l3tum/reusable-workflows/.github/workflows/publish-forgejo.yml@main
    runs-on: ubuntu-latest
    with:
      DOCKERFILE: docker/slim/Dockerfile
    secrets:
      PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
